const questions = {
    'Actual' : 'current',
    'Afan' : 'effort',
    'Afilado' : 'sharp',
    'Agrio' : 'bitter',
    'Agobiado' : 'bothered',
    'Agotado' : 'exhausted',
    'Agudo' : 'sharp',
    'Alentador' : 'encouraging',
    'Amargo' : 'bitter',
    'Angustia' : 'heartbreak',
    'Ansioso' : 'anxious',
    'Apacible' :  'gentle', 
    'Apestoso' :  'smelly',
    'Asado' : 'roasted',
    'Asombrado' : 'amazed',
    'Astucia' : 'cunning',
    'Aterrador' : 'frightening',
    'Baboso' : 'moronic',
    'Blando' : 'soft',
    'Bondad' : 'goodness',
    'Bronceado' : 'tanned',
    'Cabezon' : 'obstinate',
    'Chueco' : 'bent',
    'Colgantes' : 'hanging',
    'Comestible' : 'edible',
    'Comica' : 'funny',
    'Confundido' : 'confused',
    'Convincente' : 'convincing',
    'Corriente' : 'running',
    'Cortante' :  'sharp',
    'Cotidiano' : 'daily',
    'Crudo' : 'raw',
    'Cuadrado' : 'square',
    'Chiflado' : 'off ones head',
    'Dependiente' : 'dependent',
    'Deprimido' : 'depressed',
    'Desafiante' : 'defiant',
    'Desazon' : 'discomfort',
    'Desconcertado' : 'confused',
    'Descortes' : 'discourteous',
    'Desechado' : 'disposed',
    'Despiadado' : 'merciless',
    'Desprevenida' : 'unprepared',
    'Embarazada' : 'pregnant',
    'Empapada' : 'soaked',
    'Enojado' : 'angry',
    'Enredado' : 'tangled',
    'Escasez' : 'shortage',
    'Estrecho' : 'narrow',
    'Angosto' : 'narrow',
    'Esponjoso' : 'spongy',
    'Evitable' : 'avoidable',
    'Expectativas' : 'expectations',
    'Fatigado' : 'tired',
    'Feroz' : 'ferocious',
    'Flaco' : 'skinny',
    'Flexible' : 'flexible',
    'Flojo' : 'lazy', 
    'Fragil' : 'fragile', 
    'Fresco' : 'cool', 
    'Frito' : 'fried',
    'Frustrado' : 'frustrated',
    'Grave' : 'severe',
    'Grueso' : 'coarse',
    'Helado' : 'frozen',
    'Hervido' : 'boiled',
    'Hinchado' : 'swollen',
    'Humedo' : 'humid',
    'Incapaz' : 'incapable',
    'Inolvidable' : 'unforgettable',
    'Insolencia' : 'insolence',
    'Jaleo' : 'racket',
    'Ladeado' : 'inclined',
    'Lastima' : 'pity',
    'Liso' : 'smooth',
    'Llamativo' : 'flamboyant',
    'Llano' : 'flat',
    'Maduro' : 'mature',
    'Mudo' : 'dumb',
    'Oloroso' : 'smelly',
    'Oxidada' : 'rusty',
    'Pasmado' : 'stunned',
    'Pavoroso' : 'fearful',
    'Penoso' : 'awful',
    'Picante' : 'spicy',
    'Promedio' : 'average',
    'Provechoso' : 'rewarding',
    'Podrido' : 'rotten',
    'Quebrado' : 'broken',
    'Quemado' : 'burnt',
    'Quieto' : 'quiet',
    'Recelo' : 'distrust',
    'Redondo' : 'round',
    'Rencorosos' : 'spiteful',
    'Reparable' : 'repairable',
    'Resentido' : 'resentful',
    'Ruidoso' : 'loud',
    'Sabio' : 'wise',
    'Sabroso' : 'tasty',
    'Salado' : 'salty',
    'Salvaje' : 'wild',
    'Sedoso' : 'silky',
    'Sordo' : 'deaf',
    'Sorna' : 'irony',
    'Sorprendente' : 'surprising',
    'Sospechoso' : 'suspicious',
    'Suelto' : 'loose',
    'Tibio' : 'warm',
    'Tieso' : 'tense',
    'Trastorno' : 'upset',
    'Turbado' : 'disturbed',
    'Usado' : 'used',
    'Vacilacion' : 'hesitation',
    'Venenoso' : 'poisonous',
    'Vergonzoso' : 'embarrassed'
    };
    
    const questionBank = Object.keys(questions)
    const questionAnswer = Object.values(questions)
    let randomSort = Math.floor(Math.random() * questionAnswer.length);
    
    let questionWord = document.getElementById('question');
    let answerWord = document.getElementById('answer');
    questionWord.innerHTML = questionBank[randomSort];

    
    function reveal() {
        var x = document.getElementById("answer");
        if (x.style.display === "none") {
          x.style.display = "inline-block";
        } else {
          answerWord.innerHTML = questionAnswer[randomSort];
        }
      }

    
        function test() {
            window.location.reload();
    }